services:
  trabalho_api:
    image: gdsferreira/trabalhopooagustavo
    ports:
      - "80:8080"
    environment:
      SPRING_DATASOURCE_URL: ${BD_URL}
      SPRING_DATASOURCE_USERNAME: ${BD_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${BD_PASSWORD}
    depends_on:
      - banco
    networks:
      - trabalhopooagustavonet

  banco:
    image: postgres:17.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/home/ubuntu/dados
    networks:
      - trabalhopooagustavonet

networks:
  trabalhopooagustavonet:
volumes:
  pgdata: