name: build

on:
  push:
    branches:
      - "main"
jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - name: pegar ocodigo
        uses: actions/checkout@v4
      - name: configurar o java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'oracle'
      - name: executar o maven
        run: mvn clean install -DskipTests
      - name: gerando docker
        run: docker build -t gdsferreira/trabalhopooagustavo .
      - name: login no dockerhub
        run: docker login -u gdsferreira -p '${{ secrets.DOCKER_PASS }}'
      - name: publicar a imagem
        run: docker push gdsferreira/trabalhopooagustavo

  instalacao_aws:
    runs-on: self-hosted
    needs: construir
    steps:
      - name: pegar a imagemm
        run: sudo docker pull gdsferreira/trabalhopooagustavo
      - name: baixar o docker compose
        uses: actions/checkout@v4
      - name: gerar arquivo de env
        run: |
          cat > .env << 'EOF'
          BD_URL=${{secrets.BD_URL}}
          BD_USERNAME=${{secrets.BD_USERNAME}}
          BD_PASSWORD=${{secrets.BD_PASSWORD}}
          POSTGRES_USER=${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB=${{secrets.POSTGRES_DB}}
          DOCKER_IMAGE_NAME=gdsferreira/trabalhopooagustavo
          EOF
      - name: executar container
        run: sudo docker compose up -d --remove-orphans